### ISSUE TITLE
Issue with Sentry 24.8.0

### ISSUE THREAD

**Issue by martindaehn23** [jweslley/sentry-googlechat#5]
The legacy integration worked great until we upgraded to Sentry 24.8.0. I tried to reinstall it:
pip install sentry-googlechat
Collecting sentry-googlechat
  Downloading sentry-googlechat-10.0.0.tar.gz (4.1 kB)
  Preparing metadata (setup.py) ... done
```
INFO: pip is looking at multiple versions of sentry-googlechat to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement sentry (from sentry-googlechat) (from versions: 2.0.0a1, 2.0.0rc5, 2.0.0rc6, 2.0.0rc7, 2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.3.0, 2.3.1, 2.3.2, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.7, 2.5.0, 2.5.1, 2.5.2, 2.6.0, 2.6.1, 2.6.2, 2.7.0, 2.8.0, 2.8.1, 2.8.2, 2.9.0, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.1.4, 3.2.0, 3.3.0, 3.3.1, 3.3.2, 3.4.0, 3.4.1, 3.4.2, 3.5.0, 3.5.1, 3.5.2, 3.5.3, 3.5.4, 3.5.5, 3.5.6, 3.5.7, 3.5.8, 3.5.9, 3.6.0, 3.6.1, 3.6.2, 3.6.3, 3.6.4, 3.7.0, 3.7.1, 3.7.2, 3.7.3, 3.7.4, 3.8.0, 3.8.1, 3.8.2, 4.0.0, 4.0.1, 4.0.2, 4.0.3, 4.0.4, 4.0.5, 4.0.6, 4.0.7, 4.0.8, 4.0.9, 4.0.10, 4.0.11, 4.0.12, 4.0.13, 4.0.14, 4.0.15, 4.0.16, 4.0.17, 4.1.0, 4.1.1, 4.1.2, 4.1.3, 4.1.4, 4.1.5, 4.1.6, 4.1.7, 4.2.0, 4.2.1, 4.2.2, 4.2.4, 4.2.5, 4.3.0, 4.3.1, 4.3.2, 4.3.3, 4.4.0, 4.4.1, 4.4.2, 4.4.3, 4.4.4, 4.4.5, 4.4.6, 4.5.0, 4.5.1, 4.5.2, 4.5.3, 4.5.4, 4.5.4.1, 4.5.4.2, 4.5.5, 4.5.6, 4.5.7, 4.6.0, 4.7.0, 4.7.1, 4.7.2, 4.7.3, 4.7.4, 4.7.5, 4.7.6, 4.7.7, 4.7.8, 4.7.9, 4.8.0, 4.8.1, 4.8.2, 4.8.3, 4.8.4, 4.8.5, 4.8.6, 4.9.0, 4.9.1, 4.9.2, 4.9.3, 4.9.4, 4.9.5, 4.9.6, 4.9.7, 4.9.7.1, 4.9.8, 4.10.0, 5.0.0, 5.0.1, 5.0.2, 5.0.3, 5.0.4, 5.0.5, 5.0.6, 5.0.7, 5.0.8, 5.0.8.1, 5.0.9, 5.0.10, 5.0.11, 5.0.11.1, 5.0.12, 5.0.13, 5.0.14, 5.0.15, 5.0.16, 5.0.16.1, 5.0.17, 5.0.17.1, 5.0.17.2, 5.0.18, 5.0.18.1, 5.0.18.2, 5.0.19, 5.0.20, 5.0.20.1, 5.0.21, 5.1.0, 5.1.1, 5.1.1.1, 5.1.1.2, 5.1.2, 5.1.3, 5.1.4, 5.1.5, 5.2.0, 5.2.1, 5.2.2, 5.3.0, 5.3.1, 5.3.2, 5.3.3, 5.3.4, 5.4.0, 5.4.1, 5.4.2, 5.4.3, 5.4.4, 5.4.5, 5.4.6, 5.4.7, 6.0.0, 6.0.1, 6.0.2, 6.0.3, 6.0.4, 6.0.5, 6.0.6, 6.1.0, 6.1.1, 6.1.2, 6.2.0, 6.2.1, 6.2.2, 6.2.3, 6.3.0, 6.3.1, 6.3.2, 6.3.3, 6.4.0, 6.4.1, 6.4.2, 6.4.2.1, 6.4.3, 6.4.4, 7.0.0, 7.0.1, 7.0.2, 7.1.0, 7.1.1, 7.1.2, 7.1.3, 7.1.4, 7.2.0, 7.3.0, 7.3.1, 7.3.2, 7.4.0, 7.4.1, 7.4.3, 7.5.0, 7.5.1, 7.5.2, 7.5.3, 7.5.4, 7.5.6, 7.6.0, 7.6.2, 7.7.0, 7.7.1, 7.7.4, 8.0.0rc1, 8.0.0rc2, 8.0.0, 8.0.1, 8.0.2, 8.0.3, 8.0.4, 8.0.5, 8.0.6, 8.1.1, 8.1.2, 8.1.3, 8.1.4, 8.1.5, 8.2.0, 8.2.1, 8.2.2, 8.2.3, 8.2.4, 8.2.5, 8.3.0, 8.3.1, 8.3.2, 8.3.3, 8.4.0, 8.4.1, 8.5.0, 8.5.1, 8.6.0, 8.7.0, 8.8.0, 8.9.0, 8.10.0, 8.11.0, 8.12.0, 8.13.0, 8.14.0, 8.14.1, 8.15.0, 8.16.0, 8.16.1, 8.17.0, 8.18.0, 8.19.0, 8.20.0, 8.21.0, 8.22.0, 9.0.0rc1, 9.0.0, 9.1.0, 9.1.1, 9.1.2, 20.10.1, 20.11.0, 20.11.1, 20.12.1, 21.1.0, 21.2.0, 21.3.0, 21.3.1, 21.4.0, 21.4.1, 21.5.0, 21.5.1, 21.6.0, 21.6.1, 21.6.2, 21.6.3, 21.7.0, 21.8.0, 21.9.0, 21.10.0, 21.11.0, 21.12.0, 22.1.0, 22.2.0, 22.3.0, 22.4.0, 22.5.0, 22.6.0, 22.7.0, 22.8.0, 22.9.0, 22.10.0, 22.11.0, 22.12.0, 23.1.0, 23.1.1, 23.2.0, 23.3.0, 23.3.1, 23.4.0, 23.5.0, 23.5.1, 23.5.2, 23.6.0, 23.6.1, 23.6.2, 23.7.0, 23.7.1)
ERROR: No matching distribution found for sentry
```
And in the logs i can see:

```
cron-1                                          | Failed to load plugin 'sentry_googlechat':
cron-1                                          | Traceback (most recent call last):
cron-1                                          |   File "/usr/src/sentry/src/sentry/runner/initializer.py", line 43, in register_plugins
cron-1                                          |     plugin = ep.load()
cron-1                                          |              ^^^^^^^^^
cron-1                                          |   File "/usr/local/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
cron-1                                          |     module = import_module(match.group('module'))
cron-1                                          |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cron-1                                          |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
cron-1                                          |     return _bootstrap._gcd_import(name[level:], package, level)
cron-1                                          |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cron-1                                          |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
cron-1                                          |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
cron-1                                          |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
cron-1                                          |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
cron-1                                          |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
cron-1                                          |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
cron-1                                          |   File "/.venv/lib/python3.11/site-packages/sentry_googlechat/plugin.py", line 9, in <cron-1                                          |     from sentry.integrations import FeatureDescription, IntegrationFeatures
```

Are there any plans to implement an update to make it work on version 24.8.0?

Happy to support testing if that would help.

Thanks anyway for the effort that went into this integration!

**Comment by martindaehn23** [comment]
Sorry I missed the most important parts the last time (last two lines). It seems to have problems to import "FeatureDescription":
```
| Failed to load plugin 'sentry_googlechat':
| Traceback (most recent call last):
|   File "/usr/src/sentry/src/sentry/runner/initializer.py", line 43, in register_plugins
|     plugin = ep.load()
|              ^^^^^^^^^
|   File "/usr/local/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
|     module = import_module(match.group('module'))
|              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
|     return _bootstrap._gcd_import(name[level:], package, level)
|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
|   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
|   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
|   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
|   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
|   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
|   File "/.venv/lib/python3.11/site-packages/sentry_googlechat/plugin.py", line 9, in <module>
|     from sentry.integrations import FeatureDescription, IntegrationFeatures
| ImportError: cannot import name 'FeatureDescription' from 'sentry.integrations' (/usr/src/sentry/src/sentry/integrations/__init__.py)
```

**Comment by MRigal** [comment]
This is due to the fact that Sentry yanked all the sentry distributions on PyPI, see: https://github.com/getsentry/self-hosted/issues/1654

To fix that @jweslley , you would need to change the packaging method (not possible with setup.py), in order to install/require sentry from git, like this `pip install git+https://github.com/getsentry/sentry.git@24.8.0`

**Comment by MRigal** [comment]
Also trying to install the plugin from a local sentry install fails, as described in https://github.com/getsentry/self-hosted/issues/3337
I will make a fork without the `sentry` requirement

**Comment by MRigal** [comment]
At the end, it is just not required to have sentry as a requirement at all. See the #6 PR
